CREATE TABLE t_players(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), gameCode INT);
DROP TABLE t_events;
CREATE TABLE t_events(id INT AUTO_INCREMENT PRIMARY KEY, player VARCHAR(255), uuid VARCHAR(255), action VARCHAR(255), coins INT, gamecode VARCHAR(255))

